name: reviewbahi
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  firebase_auth: "^0.20.0+1"
  firebase_core: ^0.7.0

  url_launcher: ^3.0.0
  rflutter_alert: ^1.0.3
  scroll_app_bar: ^1.0.2


  provider: ^4.0.4
  dartz: ^0.8.9
  dio: ^3.0.9
  flutter_bloc: ^6.1.2
  shared_preferences: ^0.5.12
  dio_http_cache: ^0.2.6
  connectivity: ^0.4.9+2
  equatable: ^1.2.4
  flutter_svg: ^0.19.0
  fluttertoast: ^3.1.3
  pinput: ^1.0.0

  flutter_search_bar: ^2.1.0
  infinite_view_pager: ^1.0.0
  dots_indicator: ^1.2.0
  group_radio_button: ^1.0.1
  flutter_rating_bar: ^3.1.0
#  camera: ^0.7.0+2
#  image_picker: ^0.6.7+22

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/icons/


  fonts:
    - family: Constantia
      fonts:
        - asset: assets/fonts/Constantia-constan.ttf

